### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by utybo** [ItsAnas/awesome-epita#2]
Hi again! In order  for others to contribute, this repo needs a license, otherwise we legally can't do anything with it (can't reproduce it, modify it, adapt it...).

The choice of the license is legally entirely up to you (because you are the original author of the list). The [awesome project](https://github.com/sindresorhus/awesome/blob/main/awesome.md#choose-an-appropriate-license) recommends the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/) and I'd agree that it's a good, simple and permissive option. Just don't use a code license (MIT, GPL, MPL, Apache...) because those are only meant for code and don't work well for text.

**Comment by ItsAnas** [comment]
Hi utybo,
It should be fixed now !
I wil read carefully the **awesome project** guidelines soon to have something more structured and clean.
Thank you
